version: '3'
services:
  account:
    image: ghcr.io/hu-tao-supremacy/account-prod:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50055
      - JWT_SECRET=hu-tao-mains
    networks:
      - hts
  participant:
    image: ghcr.io/hu-tao-supremacy/participant-prod:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50056
    networks:
      - hts
  organizer:
    image: ghcr.io/hu-tao-supremacy/organizer-prod:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50057
      - HTS_SVC_ACCOUNT=account:50055
    networks:
      - hts
  personalization:
    image: ghcr.io/hu-tao-supremacy/personalization-prod:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50058
    networks:
      - hts
networks:
  hts:
    name: hts
