version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hts
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
  account:
    image: ghcr.io/hu-tao-supremacy/account-prod:latest
    ports:
      - 50055:50055
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50055
      - JWT_SECRET=hu-tao-mains
  participant:
    image: ghcr.io/hu-tao-supremacy/participant-prod:latest
    ports:
      - 50056:50056
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50056
  organizer:
    image: ghcr.io/hu-tao-supremacy/organizer-prod:latest
    ports:
      - 50057:50057
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50057
      - HTS_SVC_ACCOUNT=account:50055
  personalization:
    image: ghcr.io/hu-tao-supremacy/personalization-prod:latest
    ports:
      - 50058:50058
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50057
